version: '3.4'

networks:
  loss-detection-app_edgex-network:
    external: true   

services:
  cv-region-of-interest:
    image: rtsf-at-checkout/cv-region-of-interest:dev
    container_name: cv-region-of-interest
    hostname: cv-region-of-interest
    environment:
      - MQTT_DESTINATION_HOST=mqtt:1883
      - CAMERA0_ENDPOINT=http://video-analytic:8080/pipelines/object_detection_cpu_render/1
      - CAMERA0_SRC=rtsp://10.54.71.18:8654/simulated_camera_0.sdp
      - CAMERA0_ROI_NAME=Staging
      - CAMERA0_CROP_TBLR=475,132,795,470
      - CAMERA0_PORT=7001

      - CAMERA1_ENDPOINT=http://video-analytic:8080/pipelines/object_detection_cpu_render/1
      - CAMERA1_SRC=rtsp://10.54.71.18:8654/simulated_camera_0.sdp
      - CAMERA1_ROI_NAME=Scanner
      - CAMERA1_CROP_TBLR=475,132,795,470
      - CAMERA1_PORT=7002
    networks:
      - loss-detection-app_edgex-network
    depends_on:
      - video-analytic

  video-analytic:
    image: video-analytics-serving-gstreamer:latest
    ports:
      - "8090:8080"
      - "7001:7001"
      - "7002:7002"
    container_name: video-analytic
    hostname: video-analytic
    privileged: true
    networks:
      - loss-detection-app_edgex-network
    environment:
      DISPLAY: ${DISPLAY}
      MODEL_DIR: /models
      PIPELINE_DIR: /pipelines
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./pipelines_minimal:/pipelines
      - ./models:/models

